spring.application.name=ApiProject
spring.output.ansi.enabled=always

# Configurações do Banco de Dados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/apiproject?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Corrigido de 'jpq' para 'jpa' abaixo:
spring.jpa.show-sql=true
# Opcional: formata o SQL para ficar legível no console
spring.jpa.properties.hibernate.format_sql=true